### ISSUE TITLE
Ctrl-C causes 100% CPU load

### ISSUE THREAD

**Issue by ve7mhw** [cceremuga/pypacket#33] opened 2020-03-31 06:51 UTC
Exiting with Ctrl-C causes pypacket to exit, but one of the instances of rtl_fm remains running and goes to 100% available cpu load.  It is unaffected by kill, killall or trying to kill from htop.  This occurs on both RPi B+ and RPi3 B.  On the RPi3 B, only one core is loaded up per instance of rtl_fm, but subsequent interruption of pypacket cause more invincible instances of rtl_fm.   A reboot is the only thing that seems to clear it up.

RPi B+ running Buster lite
RPi3 B running Jesse 
python 3.6.3 on both

**Comment by ve7mhw** [comment] 2020-03-31 17:50
Upon further investigation, rtl_fm can be killed with killall -9 rtl_fm.  Also if, pypacket is halted with Ctrl-Z instead of interupted with Ctrl-C the instances of rtl_fm don't close, but none cause full load on the cpu.  Still they can not be killed with out the -9 option.

**Comment by astro-arphid** [comment] 2020-04-01 08:24
Confirming this is reproducible. 

* Raspbian Buster on Pi 3B
* Python 3.7.3

**Comment by cceremuga** [comment] 2020-04-04 13:11
Thanks for the details @ve7mhw @astro-arphid I really appreciate it. I'll take a look into this in the coming week sometime and publish a patch release.

**Comment by cceremuga** [comment] 2020-05-30 00:54
@ve7mhw @astro-arphid Thank you for your patience on this.

I think... I may have resolved this in the v5 branch if anyone would like to pull down that branch and give it a whirl. The root cause seems to be that in addition to handling KeyboardInterrupt exceptions, PyPacket also needs to handle SIGINT and properly terminate the subprocesses. I also reordered the direction in which it kills the subprocesses to be inside-out just in case it made more sense to kill the decoder before RTLFM.

We'll see. I'm not noticing any lingering issues on my Mac, but I'll try to test it in a Raspberry Pi as well.

**Comment by cceremuga** [comment] 2020-05-31 11:13
Everything seems to check out on the latest raspbian buster on the 3b+ I have in the test lab. Did a few control+c's and checked htop after to note subprocesses had successfully terminated. I'll keep testing for a few days before marking this closed for the v5 release. Naturally, if anyone reports differing results we can reopen. 😄

**Comment by Nodeswitch** [comment] 2020-05-31 14:32
@cceremuga Thanks! Testing V5 at the moment - haven't encountered the CPU issue, so all looking good so far!

**Comment by cceremuga** [comment] 2020-05-31 19:04
Gonna close this for V5 as it appears resolved. We can reopen if folks are still experiencing the issue.

**Closed by cceremuga** 2020-05-31 19:04 UTC
Labels: bug
